@TodoAPI_HostAddress = https://localhost:7212

POST {{TodoAPI_HostAddress}}/api/activity
Content-Type: application/json
{
}
###

GET {{TodoAPI_HostAddress}}/api/activity
###

GET {{TodoAPI_HostAddress}}/api/activity/{{id}}
###

DELETE {{TodoAPI_HostAddress}}/api/activity/{{id}}
###

PUT {{TodoAPI_HostAddress}}/api/activity/{{id}}
Content-Type: application/json
{
}